source 'https://rubygems.org'
ruby '3.2.2'

gem 'cocoapods', '~> 1.12.1'
gem 'fastlane', '~> 2.213.0'
gem 'fastlane-plugin-firebase_app_distribution', '~> 0.3.4'
gem 'cocoapods-keys', '~> 2.2.1'

group :development do
  gem 'cocoapods-binary', '~> 0.5.1'
  gem 'xcpretty', '~> 0.3.0'
end

group :test do
  gem 'danger', '~> 9.3.0'
  gem 'danger-swiftlint', '~> 0.33.0'
end